export const REPEATED_DOSE_TOXICITY = 'repeated-toxicity'
export const ACUTE_TOXICITY = 'acute-toxicity'
export const MUTAGENICITY = 'mutagenicity'
export const CHEMICAL_IDENTITY = 'chemical-identity'
export const SKIN_SENSITISATION_UNMERGED = 'skin-sensitisation_unmerged'
export const CARCINOGENICIY = 'carcinogenicity'
export const TOXICOKINETICS_AND_SKIN_ABSORPTION = 'toxicokinetics_skin_absorption'